# Generated by Django 2.1.3 on 2018-11-26 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=254)),
                ('path', models.CharField(max_length=254)),
                ('request_method', models.CharField(max_length=10)),
                ('request_headers', models.TextField(blank=True, default='')),
                ('request_query_string', models.TextField(blank=True, default='')),
                ('request_data', models.TextField(blank=True, default='')),
                ('response_status_code', models.IntegerField()),
                ('response_headers', models.TextField(blank=True, default='')),
                ('response_content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ApiCallback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('method', models.CharField(max_length=10)),
                ('params', models.TextField(blank=True, default='')),
                ('headers', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=254)),
                ('method', models.CharField(max_length=10)),
                ('callbacks', models.ManyToManyField(blank=True, to='mock_api.ApiCallback')),
            ],
        ),
        migrations.CreateModel(
            name='ApiResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status_code', models.IntegerField()),
                ('content', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='ApiResponseRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rule', models.CharField(max_length=50)),
                ('param_name', models.CharField(blank=True, default='', max_length=100)),
                ('param_value', models.CharField(blank=True, default='', max_length=100)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_api.ApiResponse')),
            ],
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mock_api.ApiResponse'),
        ),
        migrations.AddField(
            model_name='apiendpoint',
            name='response_rules',
            field=models.ManyToManyField(blank=True, to='mock_api.ApiResponseRule'),
        ),
        migrations.AddField(
            model_name='accesslog',
            name='api_endpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mock_api.ApiEndpoint'),
        ),
    ]
